# script.py.mako
"""Add is_neutered and notes to Pet model

Revision ID: 557af7f2f48d
Revises: f1a2b3c4d5e6
Create Date: 2026-05-15 01:05:24.017968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '557af7f2f48d'
down_revision = 'f1a2b3c4d5e6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diagnosis_results', sa.Column('report_data', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_payment_orders_id'), 'payment_orders', ['id'], unique=False)
    op.add_column('pets', sa.Column('is_neutered', sa.Boolean(), nullable=True))
    op.add_column('pets', sa.Column('notes', sa.Text(), nullable=True))
    op.create_index(op.f('ix_push_subscriptions_id'), 'push_subscriptions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_push_subscriptions_id'), table_name='push_subscriptions')
    op.drop_column('pets', 'notes')
    op.drop_column('pets', 'is_neutered')
    op.drop_index(op.f('ix_payment_orders_id'), table_name='payment_orders')
    op.drop_column('diagnosis_results', 'report_data')
    # ### end Alembic commands ###
