# script.py.mako
"""Add role and is_suspended to User, approval_status to Vet

Revision ID: 6027e17c02fd
Revises: 528392eb1bc9
Create Date: 2026-04-15 22:56:47.990022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6027e17c02fd'
down_revision = '528392eb1bc9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.String(length=20), nullable=False))
    op.add_column('users', sa.Column('is_suspended', sa.Boolean(), nullable=False))
    op.add_column('vets', sa.Column('approval_status', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vets', 'approval_status')
    op.drop_column('users', 'is_suspended')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
