# script.py.mako
"""Add profile_image_url to User model

Revision ID: dba6235a0fc0
Revises: b3e7f9a4c5d2
Create Date: 2026-05-06 01:06:59.232130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dba6235a0fc0'
down_revision = 'b3e7f9a4c5d2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_image_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_image_url')
    # ### end Alembic commands ###
